Add `threshold` and `signal` details
WICG/idle-detection pull request #41
Opened 2021-05-10 06:04 UTC by tomayac

2021-05-10 17:31 UTC, jpmedley requested changes
The expanded examples are worth a lot. Thanks

2021-05-10 17:31 UTC, jpmedley commented on mdn-drafts/QUICK-REFERENCE.md
> +with their initial values. Takes an optioanl options object with the
```suggestion
with their initial values. Takes an optional options object with the
```

2021-05-10 17:31 UTC, jpmedley commented on mdn-drafts/QUICK-REFERENCE.md
> +with their initial values. Takes an optioanl options object with the
I can't merge this to your PR.

2021-05-10 18:24 UTC, reillyeon approved these changes

2021-05-11 06:27 UTC, tomayac commented
Happy to help. This looks good to merge then.

2021-05-11 18:31 UTC, merged